### ISSUE TITLE
Stocker la position des gares et determiner un range autour

### ISSUE THREAD

**Issue by DKFN** [DKFN/edr-issues#18]
Pour pouvoir afficher:
- [x] A quelle gare est le train
- [x] Calculer la gare la plus proche du train en mouvement
- [x] Definir mieux si un train est en eloignement et pas a la gare

**Comment by Iwhite67** [comment]
Sosno : 1km

**Comment by DKFN** [comment]
Merge avec #16

**Comment by DKFN** [comment]
Prevu pour release 0.4
