### ISSUE TITLE
Sélectionner une ligne

### ISSUE THREAD

**Issue by Alex96x2** [DKFN/edr-issues#25]
Pouvoir focus une ligne en cliquant dessus.

**Comment by DKFN** [comment]
Salut par ligne, tu voudrais filtrer tous les trains qui doivent passer par la ligne 1 ou 186 par exemple c'est ca ?

**Comment by Alex96x2** [comment]
Quand tu cliques sur une ligne du tableau ça change le style de la ligne afin de pouvoir la retrouver tout de suite quand tu navigues dans le tableau.

**Comment by DKFN** [comment]
Ok, très bonne idée ! Merci

**Comment by DKFN** [comment]
Et en plus "surligner" le prochain train qui va arriver si aucune ligne a été manuellement selectionée

**Comment by itsP33t** [comment]
Translated to english and moved to https://github.com/simrail/EDR/issues/43
