### ISSUE TITLE
Style des boutons "Tous" et "En ligne"

### ISSUE THREAD

**Issue by Alex96x2** [DKFN/edr-issues#27]
Problème d'alignement et de taille des boutons en fonction de la langue

![image](https://user-images.githubusercontent.com/18704012/210276483-c9016528-86b9-4d1a-bade-a9db48145f77.png)
![image](https://user-images.githubusercontent.com/18704012/210276390-63950569-043a-424f-b8bf-0746118a8d26.png)
![image](https://user-images.githubusercontent.com/18704012/210276426-66feeedb-c653-43bb-af5c-b34e1d9d1f9e.png)

**Comment by DKFN** [comment]
Merci !

**Comment by DKFN** [comment]
Fixed version 0.6
