### ISSUE TITLE
The information bar for columns

### ISSUE THREAD

**Issue by TheFloxiCz** [DKFN/edr-issues#29]
Hi, it would be great if this bar/title can be "fixed" (= static as a search box). When you scrolling through the trains, after a few trains you cannot see name of the column.
![lišta](https://user-images.githubusercontent.com/12412419/210309283-5a3223c6-c356-4983-adda-7f275b999882.PNG)

**Comment by DKFN** [comment]
Hello !
Thanks for the issue, indeed it has been logged but in french. It is planned for a future version
I will close the french version and keep yours its better to track it in english :)
#2

**Comment by DKFN** [comment]
As expected this was quite hard to code but I can say now it works ! :partying_face: 
![image](https://user-images.githubusercontent.com/19529767/210873762-490edf9b-f98b-46db-b6ac-c55cadaa3024.png)

Thanks all, I am happy I finally managed to di this very expected feature nicely ! :smile:

**Comment by DKFN** [comment]
Released just now added to v0.5  :)
