### ISSUE TITLE
going early late - changing + and - signs

### ISSUE THREAD

**Issue by marass007** [DKFN/edr-issues#43]
Hey,  maybe wil be better to change the + and - signs at train info.  - when is early and + when is late. 
![image](https://user-images.githubusercontent.com/122229868/211221954-bc917594-08ec-4fe3-ba59-cd9b5618c3e2.png)
![image](https://user-images.githubusercontent.com/122229868/211221983-a330a89f-71d7-4faa-b839-94499ea1ae4c.png)

**Comment by DKFN** [comment]
Hey !
It seems to be a localisation issue, in france we show late trains with the - and early trains with the + (wich is confusing).
But, at the EDR is available in many languages I think it would be a good idea to add this in the localisation files of each languages. What do you think ?

Thanks for reporting !

**Comment by marass007** [comment]
I absolutely agree. It's question of localisation, we thought About this for CZ localisation. For Global purposes is there question if it's better to add this in the localisation files of each languages or just make some script which will separate localisations to two groups.

**Comment by DKFN** [comment]
I think the localisation files would be perfect for this use.
It will not add more code, and allows for locale derivates, for example fr_FR for french rules, fr_BE for belguim, fr_SN for selegal etc

**Comment by marass007** [comment]
Ok

**Comment by DKFN** [comment]
Released 0.7 thanks for the issue and the fix ! :)
