### ISSUE TITLE
We should not calculate earlyness for far away trains

### ISSUE THREAD

**Issue by DKFN** [DKFN/edr-issues#46]
It is useless to calculate the earlyness of a train if it is not around the station, this data servers no purpose.
Reported my @marass007

**Comment by Tallyrald** [comment]
How do we define not being around the station? Distance? Arriving/leaving a neighbouring station?

**Comment by DKFN** [comment]
I think we will go with distance but I'll remove this from priority as I think it indeed needs more information to be able to make it good ! :)

**Comment by Tallyrald** [comment]
This is related to https://github.com/DKFN/edr-issues/issues/63 , but it will still be a valid issue even after proper early/late calculations are implemented.

**Comment by itsP33t** [comment]
Moved to https://github.com/simrail/EDR/issues/39
