### ISSUE TITLE
Replace close button-link with more meaningful action name

### ISSUE THREAD

**Issue by Tallyrald** [DKFN/edr-issues#52]
On the top left of the EDR screen the Close button with an X is not really telling the user what is actually does. Maybe a 'Back to Server Selection' button/link would serve this purpose better. Maybe add a direct button/link to Post selection as well?

**Comment by itsP33t** [comment]
I'll have a look at it :)

**Comment by Tallyrald** [comment]
Closed by https://github.com/DKFN/better-dispatch/pull/16
