### ISSUE TITLE
Responsive issue on server select home screen

### ISSUE THREAD

**Issue by Iwhite67** [DKFN/edr-issues#55]
Problem with responsible when EDR Is use on mobile

Example : server selection 

![Screenshot_2023-01-12-07-39-07-95_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/9698964/211995956-fbf16cbe-93fc-4a18-8e50-9e2e8f0d578c.jpg)

**Comment by DKFN** [comment]
Thanks for reporting ! I detailled the title

**Comment by DKFN** [comment]
Fixed in dev branch, thanks !
