### ISSUE TITLE
Proper pathfinding

### ISSUE THREAD

**Issue by DKFN** [DKFN/edr-issues#56]
Pathfinding is used in conjunction with simple raw distance in order to
- [x] Guess if the train has passed the station
- [x] Guess an accurate ETA
- [x] Guess an accurate distance from station

This means the UI will be much less jumpy on start and while using, since most calculations are now down based on path and not on direction anymore

**Comment by DKFN** [comment]
https://github.com/DKFN/better-dispatch/pull/15

**Comment by Tallyrald** [comment]
Deployed.
