### ISSUE TITLE
Add SK to CZ text

### ISSUE THREAD

**Issue by DKFN** [DKFN/edr-issues#66]
SK and CZ are brother countries that share the same culture.

Yet, only CZ is shown because of the game server name. It will be nice to
- [x] Add slovakian to language selection
- [ ] Server name should be retargetted to "CZ/SK 1" instead of only "CZ1"
- [ ] Flag server icon should show both cz and sk flags together

Reported by Howky

**Comment by DKFN** [comment]
Nice ! Thank you very much. Someone is already doing the SK translation tho :)

**Comment by Tallyrald** [comment]
Don't want to be 'that' guy, but why would you want to merge 2 languages?
It's not that I don't want it, it's just that I don't see the point. This will also create a difference between the in-game server name and ours.

Also the flags represent languages in our case, not cultures or countries so having them both on the same server would probably create some what's going on situations.

**Comment by itsP33t** [comment]
My solution would be just to add the SK Language to the Dropdown. Like [Tallyrald](https://github.com/Tallyrald) said, it will create confusion. What do you think @DKFN

**Comment by DKFN** [comment]
Yes it will do :+1:
