### ISSUE TITLE
Lazy shows most trains as 'moving away'

### ISSUE THREAD

**Issue by Tallyrald** [DKFN/edr-issues#68]
Most of the trains at Lazy show as moving away even if they are clearly coming towards the station.

**Comment by DKFN** [comment]
![image](https://user-images.githubusercontent.com/19529767/212519452-581a8d7a-a4ce-484e-b442-ff7d5d1497b5.png)
Fixed. Lazy LC was incorrectly labelled as Lazy, this caused the pathfiding to crash, not knowing lazy.
I forgot to fix it while reviewing the pathfinding configuration.
![image](https://user-images.githubusercontent.com/19529767/212519489-da4d4ec4-be2a-4686-91db-f8f95bd8770b.png)
Thanks !
