### ISSUE TITLE
Add a sound notification when the departure badge is showing

### ISSUE THREAD

**Issue by DKFN** [DKFN/edr-issues#71]
It would be nice to have an audio clue.
It might become a bit too spammy if it is for all the trains, so it would be nice to have a Bell icon to toggle it specifically for a train and not make it default for all trains

**Comment by Valkyrien04** [comment]
Was suggesting party on discord, a specific example of this type of feature in another app would be the app Teamcraft for FFXIV. Specifically their feature for timed gathering nodes. Though the full feature is far beyond requirements here, the experience of toggling alerts for specific items is spot on.

**Comment by DKFN** [comment]
Released 0.9, thanks ! :)
