### ISSUE TITLE
Planned Open Source Release / Open Collaboration?

### ISSUE THREAD

**Issue by Perytron** [DKFN/edr-issues#73]
Are you planning to make the live map repository publically available in the future? I would be very interested in contributing to this promising project in my spare time!

I imagine myself doing some details, enhancements, things of lower importance for which you currently don't have time. Web-application-wise, I have some experience in TypeScript, PHP and obviously HTML/CSS. I've created an artillery calculator for Arma III with Leaflet (in JS), although I question some design decision I made back then. 😆

**Comment by DKFN** [comment]
Hey !
I am not the main maintainer of the map :) But afaik he is indeed planning to open source it very soon ! :)
This project ( https://edr.simrail.fr/ ) is planned to be open sourced too in one or two weeks, for version 1.0, we are at 0.8.

We would love to see your contributions and the EDR is already partially open source with a lot of help that I receive from orther develpppers.

Thanks for your interest in our project ! :)

**Comment by Perytron** [comment]
How awesome! Will there be an announcement somewhere when it opens up to the public? If not, does he have an account where I can follow to get notified for the map release?

I've already got some QOL changes and interpolation (between API calls, based on speed) in mind to make the whole experience much smoother🤩

**Comment by DKFN** [comment]
I have sent a message to the map maintainer, he should reply to you in this issue :)
See you ! :)

**Comment by Julian-Louis** [comment]
Hello, I'm the creator of the website simrail.fr, can you add me on discord please ? (Sumonil#0001)
