### ISSUE TITLE
Add streamer mode / mobile mdoe

### ISSUE THREAD

**Issue by DKFN** [DKFN/edr-issues#74]
Add some informations when the users enters "condensed" mode that would allow a better display on mobile devices or small screens

**Comment by itsP33t** [comment]
What should the Streamer mode do?

**Comment by DKFN** [comment]
Well its basically the same as the mobile mode, just hide a bunch of stuff that takes a lot of space like the train picutre and maybe display the station condensed name (DGW for example instead of the full name" of the station for small screen resolutions basically :)

**Comment by itsP33t** [comment]
I can look at that when i'm feeling better

**Comment by DKFN** [comment]
Take care, there is no rush :)

**Comment by DKFN** [comment]
Due to some urging requests from a few streamers, I took the liberty of doing it.
Should be released in 1.1 ! :)
