### ISSUE TITLE
Déplacer le point de Sosno

### ISSUE THREAD

**Issue by TheMulhoose** [DKFN/edr-issues#8]
Voir si c'est possible de pouvoir mettre le point de Sosno au centre de la gare pour ne pas déclencher un départ au passage du poste d'aiguillage quand un train va vers Bedzin alors que celui-ci n'est pas encore en gare

**Comment by DKFN** [comment]
Merci en effet :+1:

**Comment by DKFN** [comment]
Malheuresement, pour l'instant seuls les points des postes sont dispos par l'API.
En revanche ca serait interessant de mettre plutot les points des gares nous meme, par contre ca va pas etre tout de suite mais je garde la suggestion pour plus tard :)

**Comment by DKFN** [comment]
Ticket remplacé par #18  et passé en priorité
