### ISSUE TITLE
Chrome not loading new data

### ISSUE THREAD

**Issue by xEtarusx** [DKFN/edr-issues#81]
Hello,
it looks like Chrome does not load new data via ajax (or whatever). I have the newest chrome version 109.0.5414.75.
If I use my FireFox browser the ajax requests work fine and the data is updated every 10 seconds.

Could somebody please double check if there is a problem with chrome and asynchronous data loading with the edr page of any station?

**Comment by Tallyrald** [comment]
Works fine for me. Could you try force-reloading the page with Ctrl+F5? Also can you please check if there are any errors in the console (F12, look for the console tab at the bottom)?

**Comment by xEtarusx** [comment]
No errors in the console. Only one i18next warning `i18next::backendConnector: loading namespace translation for language en-US failed failed parsing /locales/en-US/translation.json to json`.
Already tried Ctrl+F5 but it does not help.

**Comment by DKFN** [comment]
Hey thank you very much for reporting the issue :)

I think there is something we cannot grasp either in your extensions or security policies of your browser that is making the data refresh code crash :thinking: 

I also use Chrome 109 while using and developping the app.
Maybe it is not wise to disclose such informations on a public issue but If could contact me on Discord at `DeadlyKungFu.Ninja#8294`  it might help a lot.

Thanks again ! :)

**Comment by Tallyrald** [comment]
Is there new information regarding this? Do we know what caused it or whether we can do something to prevent it?

**Comment by DKFN** [comment]
So far I have not been able to reproduce it. Our initial guess was Dashlane, but I tried with the extension too and could not reproduce it despite indeed having the same error messages in the console.

Maybe, it has been fixed in the latest versions because the code got cleaner from version to version, especially, I have removed all the anti patterns used as a shortcut that made some extensions and browsers (especially Edge) choke on some DOM Elements

**Comment by xEtarusx** [comment]
It looks like the problem has been fixed. Version 1.0 runs without any problems on my chrome now. Data refreshing is now working properly. 👍

**Comment by DKFN** [comment]
Awesome, thanks for letting us know about it ! :) 
See you soon !
