### ISSUE TITLE
Map doesn't load

### ISSUE THREAD

**Issue by Tallyrald** [DKFN/edr-issues#82]
Opening the new map popup shows a client side error.
![image](https://user-images.githubusercontent.com/35098410/213394837-bc89bfa7-ec9a-40e4-9df4-99d1b02078c7.png)

**Comment by DKFN** [comment]
Hey !

I beleive you are accessing from edr.deadlykungfu.ninja can you check if you have the same error with https://edr.simrail.fr/ ?
It is probably a cross domain security policy that we forgot about :D 

Thanks !

**Comment by Tallyrald** [comment]
Oh you're right, didn't realise the URL changed. Never mind then :D

**Comment by DKFN** [comment]
Well, still a bug, but now I can pinpoint exactly where. Thanks :smile:

**Comment by DKFN** [comment]
Seems the issue has been fixed on the map end. Thanks ! :)
