### ISSUE TITLE
Add a toast library to inform users when retrying is in progress or refresh interval failed to subscribe

### ISSUE THREAD

**Issue by DKFN** [DKFN/edr-issues#83]

**Comment by Tallyrald** [comment]
I was thinking of [Notistack](https://github.com/iamhosseindhv/notistack) since it integrates with React seamlessly. We could also use it for https://github.com/DKFN/edr-issues/issues/80 to confirm the copy to clipboard actually happened.

**Comment by DKFN** [comment]
Great idea, it looks pretty cool :)
