### ISSUE TITLE
Make departing status one minute before actual departure

### ISSUE THREAD

**Issue by DKFN** [DKFN/edr-issues#85]
This to let the dispatcher have time to open the route

**Comment by DKFN** [comment]
I wonder if its not work adding a "Prepare for departure" or something, wdyt ? :)

**Comment by Tallyrald** [comment]
I would say it's unnecessary complexity. The dispatcher needs simple, easy to understand info and since the departure time is right next to the badge I would think the current badge is more than enough.

**Comment by DKFN** [comment]
Agreed, and given the server time is not actually synced with normal time currently, this also gives more leanway for the dispatcher to that.
Thanks for the PR ! :)
