### ISSUE TITLE
Wrong Name - Zadajnik jazdy

### ISSUE THREAD

**Issue by P1T0T** [DKFN/edr-issues#93]
Hi, 
Instead of name "Zadajnik jazdy" it should be named "Nastawnik jazdy"
Even if you type in google "Zadajnik jazdy" it doesn't show up anything close to "Nastawnik Jazdy".

![image](https://user-images.githubusercontent.com/118312739/213908131-2b8282a4-65fc-427f-80c4-b580d2cdde77.png)

**Comment by DKFN** [comment]
Hello,
We are not the developpers of the game Simrail, we are the developpers of a community mod https://edr.simrail.fr/

Have a good day! :)
