### ISSUE TITLE
Add occupation indicator to servers and posts

### ISSUE THREAD

**Issue by Tallyrald** [DKFN/edr-issues#94]
- For the server list, we could add either an occupation count for dispatch posts or maybe a detailed list on mouse hover event.
- For the post list, we could add a small Steam avatar / Steam name for occupied posts.

What do you think?

**Comment by DKFN** [comment]
Yes, I think we should wait for the redesign to implement it tho. Wdyt ?

**Comment by itsP33t** [comment]
Moved to https://github.com/simrail/EDR/issues/32
