### ISSUE TITLE
Add descriptions to icons

### ISSUE THREAD

**Issue by tpeterka1** [DKFN/edr-issues#96]
My suggestion is to add some description text when hovering your mouse over these icons, because some people may not understand them at first. I would also add some text to the bell icon and the map icon.
![image](https://user-images.githubusercontent.com/63014892/214110481-95289d30-3bff-4474-a357-50adacfca135.png)

**Comment by DKFN** [comment]
Thanks ! Great idea :)

**Comment by Tallyrald** [comment]
Implemented by [@flow](https://github.com/Flows-copr), thanks!
